#!/bin/bash 

# String to be prefixed to compressed file names
BAK_NAME=...

# Database backup parameters
DB_NAME=...
DB_USER=...
DB_PASS=...
DB_HOST=...

# Directory to include in files backup
DIRECTORY=...

# Timezone to be used on backup filename
TIMEZONE=...
